# Generated by Django 3.1.2 on 2020-12-09 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='categories',
            field=models.ManyToManyField(to='product.Category', verbose_name='Categories of Store'),
        ),
        migrations.AddField(
            model_name='store',
            name='sub_categories',
            field=models.ManyToManyField(to='product.SubCategory', verbose_name='Sub Categories of Store'),
        ),
    ]
