# Generated by Django 3.1.3 on 2020-11-17 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_auto_20201117_1149'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='address.address'),
        ),
    ]
