# Generated by Django 3.1.2 on 2020-12-28 07:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20201226_1834'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pardakht', '0003_auto_20201228_1125'),
    ]

    operations = [
        
        migrations.AddField(
            model_name='cart',
            name='product',
            field=models.ManyToManyField(through='pardakht.CartItems', to='product.Product'),
        ),
    ]
