# Generated by Django 3.1.2 on 2020-12-28 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pardakht', '0004_auto_20201228_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitems',
            name='qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='cartitems',
            constraint=models.UniqueConstraint(fields=('cart', 'product'), name='unique_cartitems'),
        ),
    ]
