# Generated by Django 3.1.2 on 2020-12-13 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user_join_date', models.DateField(auto_created=True)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, primary_key=True, serialize=False, to='auth.user')),
                ('phonenumber', models.CharField(max_length=12)),
                ('ful_name', models.CharField(max_length=40)),
                ('postal_code', models.IntegerField()),
                ('password', models.CharField(max_length=128)),
                ('image', models.ImageField(blank=True, null=True, upload_to='./res/profile_photo')),
                ('user_type', models.CharField(choices=[('A', 'customer'), ('B', 'staff')], default='A', max_length=1)),
                ('user_last_login', models.DateTimeField(blank=True, null=True)),
                ('address', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.address')),
            ],
        ),
    ]
