# Generated by Django 3.1.2 on 2020-12-18 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20201213_1204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user_id',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_join_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_last_login',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
