# Generated by Django 3.1.2 on 2020-12-18 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20201218_2319'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='id',
            new_name='user',
        ),
    ]
