<<<<<<< HEAD
# Generated by Django 3.1.2 on 2021-01-15 18:32

from django.conf import settings
=======
# Generated by Django 3.1.2 on 2020-12-13 08:17

>>>>>>> parent of b717f21... migration
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('address_detail', models.TextField(blank=True, null=True)),
                ('poste_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='کدپستی')),
                ('priority_address', models.SmallIntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
=======
                ('city', models.CharField(max_length=30)),
                ('detail', models.JSONField(blank=True, null=True)),
>>>>>>> parent of b717f21... migration
            ],
        ),
    ]
