# Generated by Django 3.1.2 on 2021-01-15 17:34
from django.contrib.postgres.operations import CreateExtension

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        CreateExtension('postgis'),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326, verbose_name='موقعیت جغرافیایی')),
                ('address_detail', models.TextField(blank=True, null=True)),
                ('poste_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='کدپستی')),
                ('priority_address', models.SmallIntegerField(default=1)),
            ],
        ),
    ]
