# Generated by Django 3.1.2 on 2021-01-20 11:56

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0002_auto_20210120_1526'),
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326, verbose_name='موقعیت جغرافیایی')),
                ('address_detail', models.TextField(blank=True, null=True)),
                ('poste_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='کدپستی')),
                ('priority_address', models.SmallIntegerField(default=1)),
                ('working_raduis', models.IntegerField(default=100)),
            ],
        ),
        migrations.RenameModel(
            old_name='Address',
            new_name='UserAddress',
        ),
        migrations.AddConstraint(
            model_name='useraddress',
            constraint=models.UniqueConstraint(fields=('user', 'priority_address'), name='unique_priority_user_location'),
        ),
        migrations.AddField(
            model_name='storeaddress',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.store'),
        ),
        migrations.AddConstraint(
            model_name='storeaddress',
            constraint=models.UniqueConstraint(fields=('store', 'priority_address'), name='unique_priority_store_location'),
        ),
    ]
