# Generated by Django 3.1.4 on 2021-01-12 20:14
from django.contrib.postgres.operations import CreateExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        CreateExtension('postgis')
    ]
