# Generated by Django 3.1.2 on 2021-01-22 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0001_initial'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeaddress',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.store'),
        ),
        migrations.AddConstraint(
            model_name='useraddress',
            constraint=models.UniqueConstraint(fields=('user', 'priority_address'), name='unique_priority_user_location'),
        ),
        migrations.AddConstraint(
            model_name='storeaddress',
            constraint=models.UniqueConstraint(fields=('store', 'priority_address'), name='unique_priority_store_location'),
        ),
    ]
