# Generated by Django 3.1.4 on 2021-01-12 20:38

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('address', '0002_auto_20210112_2344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='city',
        ),
        migrations.RemoveField(
            model_name='address',
            name='detail',
        ),
        migrations.AddField(
            model_name='address',
            name='address_detail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(default=django.utils.timezone.now, geography=True, srid=4326, verbose_name='موقعیت جغرافیایی'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='poste_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='کدپستی'),
        ),
        migrations.AddField(
            model_name='address',
            name='priority_address',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='address',
            name='user',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='user.user'),
            preserve_default=False,
        ),
    ]
