(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var h="function"==typeof Object.create?Object.create:function(a){var b=function(){};b.prototype=a;return new b},m;if("function"==typeof Object.setPrototypeOf)m=Object.setPrototypeOf;else{var n;a:{var p={l:!0},q={};try{q.__proto__=p;n=q.l;break a}catch(a){}n=!1}m=n?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var r=m;var t=function(a){return!(a.ownerDocument.compareDocumentPosition(a)&Node.DOCUMENT_POSITION_DISCONNECTED)};var u=function(a){var b=void 0===b?null:b;var c=document.createEvent("CustomEvent");c.initCustomEvent("gwdfontsloaded",!0,!0,b);a.dispatchEvent(c)};var w=function(){var a=HTMLElement.call(this)||this;a.f=[];a.a=null;a.j=a.h.bind(a,!0);a.i=a.h.bind(a,!1);a.c=null;a.b=null;return a},x=HTMLElement;w.prototype=h(x.prototype);w.prototype.constructor=w;if(r)r(w,x);else for(var y in x)if("prototype"!=y)if(Object.defineProperties){var z=Object.getOwnPropertyDescriptor(x,y);z&&Object.defineProperty(w,y,z)}else w[y]=x[y];w.prototype.disconnectedCallback=function(){B(this)};
w.prototype.startDynamicFontLoading=function(){this.a&&(B(this),this.a.parentElement.removeChild(this.a),this.a=null);this.f=[];this.c=null};
w.prototype.parseFontList=function(a){if(void 0!=a){a=a.trim();for(var b="",c=0,e=!1,d=0;d<a.length;d++)if('"'==a[d]&&(e=!e),!(e||","!=a[d]&&d!=a.length-1)){c=a.substring(c,","==a[d]?d:d+1).trim();var f=c.indexOf("https://fonts.googleapis.com/css?family=");if(0==f||1==f){'"'==c[0]&&'"'==c[c.length-1]?this.f.push(c.substring(1,c.length-1)):this.f.push(c);f+=40;var g=c.indexOf(":",f);-1==g&&(g='"'==c[c.length-1]?c.length-1:c.length);c=c.substring(f,g);c=c.length?'"'+c.replace(/[+]/g," ")+'"':""}c&&
(0<b.length&&(b+=", "),b+=c);c=d+1}return b}};
w.prototype.endDynamicFontLoading=function(){var a=this.ownerDocument;if(!a)return!0;for(var b=C(a),c=D(this.f),e=Object.keys(c),d=0;d<e.length;d++){for(var f=e[d],g=c[f],k=b[f]||{},l=Object.keys(g),v=0;v<l.length;v++){var A=l[v];k[A]&&delete g[A]}0==Object.keys(g).length&&delete c[f]}e=Object.keys(c).sort();if(0==e.length)return!0;b="";for(d=0;d<e.length;d++)f=e[d],g=Object.keys(c[f]).sort(),k=g.indexOf("default"),-1<k&&(0<b.length&&(b+="|"),b+=f,g.splice(k,1)),0<g.length&&(0<b.length&&(b+="|"),
b+=f+":"+g.join(","));this.a=a.createElement("link");this.a.setAttribute("rel","stylesheet");this.a.setAttribute("type","text/css");this.a.setAttribute("href","https://fonts.googleapis.com/css?family="+b);this.ownerDocument.fonts&&this.ownerDocument.fonts.load?(this.c=e.map(function(E){return'"'+E.replace(/[+]/g," ")+'"'}),this.a.addEventListener("load",this.j,!1),this.a.addEventListener("error",this.i,!1)):F(this,e);a.head.insertBefore(this.a,a.head.querySelector("style"));return!1};
var C=function(a){a=Array.prototype.slice.call(a.querySelectorAll('link[href^="https://fonts.googleapis.com/css?family="]')).map(function(b){return b.getAttribute("href")});return D(a)},D=function(a){for(var b={},c=0;c<a.length;c++)for(var e=a[c].substring(40).split("|"),d=0;d<e.length;d++){var f=e[d].indexOf(":"),g=-1==f?e[d]:e[d].substring(0,f),k=b[g]||{};if(-1==f||f==e[d].length-1)k["default"]=!0;else{f=e[d].substring(f+1).split(",");for(var l=0;l<f.length;l++)k[f[l]]=!0}b[g]=k}return b};
w.prototype.h=function(a,b){if(t(this)&&this.a&&b.target==this.a)if(B(this),a&&this.c&&0!=this.c.length){a=this.ownerDocument;b=Array.prototype.slice.call(this.c);for(var c=0;c<b.length;c++){var e=this.m.bind(this,b[c],this.c);a.fonts.load("12px "+b[c]).then(e,e)}}else u(this)};w.prototype.m=function(a,b){b==this.c&&(a=b.indexOf(a),-1!=a&&(b.splice(a,1),0==b.length&&u(this)))};
var F=function(a,b){a.b=[];for(var c=[],e=[],d=0;d<b.length;d++)for(var f=0;2>f;f++){var g=a.ownerDocument.createElement("div");g.className="gwdfontloaderprobe";g.textContent="Sample text";g.style.opacity=0;g.style.position="absolute";g.style.width="auto";g.style.height="auto";g.style.fontFamily='"'+b[d]+'",'+(0==f?"Arial":"Arial Black");a.ownerDocument.body.appendChild(g);a.b.push(g);c.push(g.offsetWidth);e.push(g.offsetHeight)}setTimeout(a.g.bind(a,c,e,0),50)};
w.prototype.g=function(a,b,c){if(t(this)&&this.b&&!this.b.some(function(f){return!t(f)})){for(var e=!0,d=0;d<this.b.length/2;d++)if(this.b[2*d].offsetWidth==a[2*d]&&this.b[2*d].offsetHeight==b[2*d]&&this.b[2*d+1].offsetWidth==a[2*d+1]&&this.b[2*d+1].offsetHeight==b[2*d+1]){e=!1;break}c++;e||40==c?(B(this),u(this)):setTimeout(this.g.bind(this,a,b,c),50)}};
var B=function(a){if(a.ownerDocument.fonts&&a.ownerDocument.fonts.load)a.a&&(a.a.removeEventListener("load",a.j,!1),a.a.removeEventListener("error",a.i,!1));else if(a.b){for(var b=0;b<a.b.length;b++){var c=a.b[b];t(c)&&c.parentElement.removeChild(c)}a.b=null}};customElements.define("gwd-font-loader",w);}).call(this);
