(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var d="function"==typeof Object.create?Object.create:function(a){var b=function(){};b.prototype=a;return new b},k=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");},l=k(this),n;
if("function"==typeof Object.setPrototypeOf)n=Object.setPrototypeOf;else{var p;a:{var q={l:!0},t={};try{t.__proto__=q;p=t.l;break a}catch(a){}p=!1}n=p?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var u=n;var v="currentIndex frameCount frameSnapInterval getFrame goToFrame goForwards goBackwards rotateOnce".split(" ");var w={s:"for",u:"highlight",v:"use-thumbnails"},x=[],y=0,z;for(z in w)x[y++]=w[z];var A=function(){var a=HTMLElement.call(this)||this;a.a=null;a.i=a.o.bind(a);a.h=a.m.bind(a);a.g=!1;a.b=null;a.c=[];a.f=!1;return a},B=HTMLElement;A.prototype=d(B.prototype);A.prototype.constructor=A;if(u)u(A,B);else for(var C in B)if("prototype"!=C)if(Object.defineProperties){var D=Object.getOwnPropertyDescriptor(B,C);D&&Object.defineProperty(A,C,D)}else A[C]=B[C];
A.prototype.connectedCallback=function(){if(!this.f){for(;this.firstChild;)this.removeChild(this.firstChild);this.b=this.ownerDocument.createElement("div");this.b.classList.add("button-container");this.appendChild(this.b);this.f=!0}this.b.addEventListener("click",this.j.bind(this),!0);E(this)};A.prototype.disconnectedCallback=function(){this.b.removeEventListener("click",this.j.bind(this));F(this)};A.prototype.attributeChangedCallback=function(a){if(this.f)switch(a){case "for":E(this);break;default:G(this)}};
var E=function(a){F(a);var b=a.getAttribute("for"),c=null,f=!1;if(b){c=document.getElementById(b);for(var g=!1,e=a.parentElement;!c&&e&&!g;e=e.parentElement)if((g="body"==e.tagName.toLowerCase())||e.hasAttribute("data-gwd-group"))c=e.querySelector('[data-gwd-grp-id="'+b+'"]');if(c)a:if(c){for(b=0;b<v.length;b++)if(!(v[b]in c)){f=!1;break a}f=!0}else f=!1}f&&(a.a=c,c.addEventListener("frameactivated",a.h),c.gwdIsLoaded()?G(a):c.addEventListener("ready",a.i))},F=function(a){a.a&&(a.a.removeEventListener("ready",
a.i),a.a.removeEventListener("frameactivated",a.h))};A.prototype.o=function(a){a.target==this.a&&G(this)};A.prototype.m=function(a){a.target==this.a&&H(this,a.detail.id)};A.prototype.j=function(a){for(a=a.target;a&&a!=this;a=a.parentElement)if(a.gwdTargetFrameNum){this.a.goToFrame(a.gwdTargetFrameNum);break}};
var G=function(a){var b=a.getAttribute("highlight");a.style.color=b||"";a.g=a.hasAttribute("use-thumbnails");for(a.c=[];a.b.firstChild;)a.b.removeChild(a.b.firstChild);if(a.a){b=a.a.frameSnapInterval||1;for(var c=a.g?b:1,f=0;f<a.a.frameCount;f+=b){var g=document.createElement("span");g.classList.add("button");for(var e=0;e<c;e++){var h=a.a.getFrame(f+e+1);if(!h)break;var r=void 0,m=document.createElement("span");a.g?(m.classList.add("frame-thumbnail"),(h="gwd-image"==h.tagName.toLowerCase()||"img"==
h.tagName.toLowerCase()?h:h.querySelector("gwd-image"))&&(r=h.getAttribute("source")||h.getAttribute("src")),m.style.backgroundImage=r?"url("+JSON.stringify(r)+")":"url(data:image/gif;base64,R0lGODlhAQABAPAAAGZmZgAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==)"):m.classList.add("frame-dot");g.appendChild(m)}g.gwdTargetFrameNum=f+1;a.c.push(g);a.b.appendChild(g)}H(a)}},H=function(a,b){b=void 0!=b?b-1:a.a.currentIndex-1;a.a.frameSnapInterval&&(b=Math.floor(b/a.a.frameSnapInterval));for(var c=0;c<a.c.length;c++)a.c[c].classList.remove("active");
(a=a.c[b])&&a.classList.add("active")};l.Object.defineProperties(A,{observedAttributes:{configurable:!0,enumerable:!0,get:function(){return x}}});customElements.define("gwd-gallerynavigation",A);}).call(this);
