(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var g,h="function"==typeof Object.create?Object.create:function(a){var b=function(){};b.prototype=a;return new b},k;if("function"==typeof Object.setPrototypeOf)k=Object.setPrototypeOf;else{var l;a:{var n={aa:!0},p={};try{p.__proto__=n;l=p.aa;break a}catch(a){}l=!1}k=l?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}
var q=k,r=this||self,t=function(a,b){a=a.split(".");var c=r;a[0]in c||"undefined"==typeof c.execScript||c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)a.length||void 0===b?c=c[d]&&c[d]!==Object.prototype[d]?c[d]:c[d]={}:c[d]=b};var u=function(){this.B={}};u.prototype.add=function(a,b){a="string"===typeof a?a:a.getString();this.B[a]||(this.B[a]=[]);this.B[a].push(b)};var v=function(a){var b=[],c="object"==typeof gwd&&"GwdId"in gwd,d;for(d in a.B)b.push(c?new gwd.GwdId(d):d);return b},w=function(a,b){return b?a.B["string"===typeof b?b:b.getString()]||[]:[]};var x=function(a,b){if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||!!(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a},y=function(a){return"gwd-page"==a.tagName.toLowerCase()||"gwd-page"==a.getAttribute("is")},z=function(a){if(y(a))return a;for(;a&&9!=a.nodeType;)if((a=a.parentElement)&&y(a))return a;return null};var A=function(a,b){this.i=a;this.ba=b;this.I=this.N.bind(this)};A.prototype.observe=function(a){if(a.nodeType==Node.ELEMENT_NODE)for(var b=v(this.i),c=0;c<b.length;c++){var d=C(b[c]);if(d&&x(a,d)){var e=w(this.i,b[c]);if(e)for(var f=0;f<e.length;f++)d.addEventListener(e[f].event,this.I,!1)}}};A.prototype.N=function(a){this.ba(a)};var C=function(a){return"string"===typeof a?document.getElementById(a):a.getElement(document)};var D=function(a,b,c){c=void 0===c?null:c;var d=document.createEvent("CustomEvent");d.initCustomEvent(a,!0,!0,c);b.dispatchEvent(d);return d};Object.freeze&&Object.freeze([]);var E=function(a,b){var c=r.performance;a={label:a,type:9,value:c&&c.now&&c.timing?Math.floor(c.now()+c.timing.navigationStart):Date.now()};b=b.google_js_reporting_queue=b.google_js_reporting_queue||[];2048>b.length&&b.push(a)};var F={},G=!1,H=!1;F.W=function(a){G||(G=!0,E("11",a))};F.na=function(a){H||(H=!0,E("12",a))};F.oa=function(a,b,c){var d=b;d=void 0===d?r:d;if(d=(d=d.performance)&&d.now?d.now():null)a={label:a,type:void 0===c?0:c,value:d},b=b.google_js_reporting_queue=b.google_js_reporting_queue||[],2048>b.length&&b.push(a)};F.reset=function(a){H=G=!1;(a.google_js_reporting_queue=a.google_js_reporting_queue||[]).length=0};t("gwd.rumUtil",F);t("gwd.rumUtil.logContentLoading",F.W);
t("gwd.rumUtil.logContentRendered",F.na);t("gwd.rumUtil.logTimingEvent",F.oa);t("gwd.rumUtil.reset",F.reset);var I=function(){var a=HTMLElement.call(this)||this;a.T=a.ha.bind(a);a.L=a.ja.bind(a);a.U=a.ia.bind(a);a.F=a.ga.bind(a);a.D=a.ea.bind(a);a.G=D.bind(null,"expandfinish",a);a.C=D.bind(null,"collapsefinish",a);a.S=a.fa.bind(a);a.s=a.ma.bind(a);a.I=a.N.bind(a);a.Y=a.ka.bind(a);a.$=a.la.bind(a);a.h=null;a.c=null;a.A=!1;a.v=!1;a.O=[];a.l=!1;a.K=!1;a.u=null;a.m=!1;a.H=!1;a.J=window.innerHeight>=window.innerWidth?1:2;a.b=null;a.g=null;a.j=null;a.V=!1;a.R=!1;return a},J=HTMLElement;I.prototype=h(J.prototype);
I.prototype.constructor=I;if(q)q(I,J);else for(var K in J)if("prototype"!=K)if(Object.defineProperties){var L=Object.getOwnPropertyDescriptor(J,K);L&&Object.defineProperty(I,K,L)}else I[K]=J[K];g=I.prototype;
g.connectedCallback=function(){var a=this;this.V||(this.K=this.hasAttribute("fullscreen"),document.body.style.opacity="0",this.V=!0);Enabler.addEventListener(studio.events.StudioEvent.EXPAND_START,this.F);Enabler.addEventListener(studio.events.StudioEvent.COLLAPSE_START,this.D);Enabler.addEventListener(studio.events.StudioEvent.FULLSCREEN_EXPAND_START,this.F);Enabler.addEventListener(studio.events.StudioEvent.FULLSCREEN_COLLAPSE_START,this.D);Enabler.addEventListener(studio.events.StudioEvent.EXPAND_FINISH,
this.G);Enabler.addEventListener(studio.events.StudioEvent.COLLAPSE_FINISH,this.C);Enabler.addEventListener(studio.events.StudioEvent.FULLSCREEN_EXPAND_FINISH,this.G);Enabler.addEventListener(studio.events.StudioEvent.FULLSCREEN_COLLAPSE_FINISH,this.C);Enabler.addEventListener(studio.events.StudioEvent.FULLSCREEN_DIMENSIONS,this.S);window.addEventListener("resize",this.$,!1);(0,F.W)(window);setTimeout(function(){a.a=a.querySelector("gwd-pagedeck");a.a.addEventListener("pagetransitionend",a.Y,!1);
a.b=document.getElementById(a.getAttribute("data-provider"));a.g=document.querySelector("gwd-data-binder");a.j=document.querySelector("gwd-responsive-attributes-helper");a.j&&a.j.applyOverrides();var b=a.querySelector("gwd-metric-configuration"),c=new u;if(b){b=Array.prototype.slice.call(b.getElementsByTagName("gwd-metric-event"));for(var d=0;d<b.length;d++){var e=b[d],f=e.getAttribute("source");if(f){var m=e.getAttribute("exit");e={event:e.getAttribute("event"),pa:e.getAttribute("metric")||m,ca:e.hasAttribute("cumulative"),
exit:m};c.add(M(f),e)}}}a.i=c;a.X=new A(a.i,a.I)},0)};
g.disconnectedCallback=function(){Enabler.removeEventListener(studio.events.StudioEvent.INIT,this.T);Enabler.removeEventListener(studio.events.StudioEvent.VISIBLE,this.L);Enabler.removeEventListener(studio.events.StudioEvent.PAGE_LOADED,this.U);Enabler.removeEventListener(studio.events.StudioEvent.EXPAND_START,this.F);Enabler.removeEventListener(studio.events.StudioEvent.COLLAPSE_START,this.D);Enabler.removeEventListener(studio.events.StudioEvent.FULLSCREEN_EXPAND_START,this.F);Enabler.removeEventListener(studio.events.StudioEvent.FULLSCREEN_COLLAPSE_START,
this.D);Enabler.removeEventListener(studio.events.StudioEvent.EXPAND_FINISH,this.G);Enabler.removeEventListener(studio.events.StudioEvent.COLLAPSE_FINISH,this.C);Enabler.removeEventListener(studio.events.StudioEvent.FULLSCREEN_EXPAND_FINISH,this.G);Enabler.removeEventListener(studio.events.StudioEvent.FULLSCREEN_COLLAPSE_FINISH,this.C);Enabler.removeEventListener(studio.events.StudioEvent.FULLSCREEN_DIMENSIONS,this.S);this.a.removeEventListener("pagetransitionend",this.Y,!1);window.removeEventListener("resize",
this.$,!1);this.b&&this.h&&this.b.removeEventListener("ready",this.h);this.g&&this.c&&this.g.removeEventListener("bindingfinished",this.c);Enabler.removeEventListener(studio.events.StudioEvent.HOSTPAGE_SCROLL,this.s,!1);window.removeEventListener("message",this.s,!1)};g.initAd=function(){this.l=!1;var a=this.T;Enabler.removeEventListener(studio.events.StudioEvent.INIT,a);Enabler.addEventListener(studio.events.StudioEvent.INIT,a);Enabler.isInitialized()&&a()};
g.exit=function(a,b,c,d,e){c=void 0===c?!1:c;d=void 0===d?!0:d;Enabler.exit(a,b);d&&N(this);c&&this.goToPage(e)};g.exitOverride=function(a,b,c,d,e){c=void 0===c?!1:c;d=void 0===d?!0:d;Enabler.exitOverride(a,b);d&&N(this);c&&this.goToPage(e)};g.incrementCounter=function(a,b){Enabler.counter(a,b)};g.startTimer=function(a){Enabler.startTimer(a)};g.stopTimer=function(a){Enabler.stopTimer(a)};g.reportManualClose=function(){Enabler.reportManualClose()};
g.N=function(a){var b=a.target,c=M(b),d=c+": "+a.type;a:{var e=w(this.i,c);for(var f=0;f<e.length;f++)if(e[f].event==a.type){e=e[f];break a}e=void 0}e.exit&&a.detail&&a.detail.url?(d=c+": "+e.exit,a.detail["exit-id"]&&(d=a.detail["exit-id"]),b="",null!=a.detail["product-index"]&&(b=a.detail["product-index"]),this.b&&0==(this.b.getAttribute("gwd-schema-id")||"").indexOf("dynamic_remarketing")?(c=a.detail["action-event"],e={},c&&(e.clickX=c.clientX||c.changedTouches[0].clientX,e.clickY=c.clientY||c.changedTouches[0].clientY),
Enabler.dynamicExit(d,a.detail.url,b,void 0,e)):Enabler.exitOverride(d,a.detail.url),a.detail.handled=!0,a.detail.collapse&&this.goToPage()):(a=z(b))&&a.gwdIsActive()&&this.incrementCounter(e.pa||d,e.ca)};
g.ha=function(){var a=this;Enabler.removeEventListener(studio.events.StudioEvent.HOSTPAGE_SCROLL,this.s,!1);window.removeEventListener("message",this.s,!1);Enabler.isServingInLiveEnvironment()?Enabler.addEventListener(studio.events.StudioEvent.HOSTPAGE_SCROLL,this.s,!1):window.addEventListener("message",this.s,!1);var b=function(){if(a.hasAttribute("polite-load")){var d=a.U;Enabler.isPageLoaded()?d():Enabler.addEventListener(studio.events.StudioEvent.PAGE_LOADED,d)}else d=a.L,Enabler.isVisible()?
d():Enabler.addEventListener(studio.events.StudioEvent.VISIBLE,d)};if(this.K){var c=function(d){a.u=!!d.supported;a.u&&D("fullscreensupport",a);Enabler.removeEventListener(studio.events.StudioEvent.FULLSCREEN_SUPPORT,c);b()};Enabler.addEventListener(studio.events.StudioEvent.FULLSCREEN_SUPPORT,c);Enabler.queryFullscreenSupport()}else b()};
g.ja=function(a){var b=this;if(this.l)this.b&&O(this,null);else{var c;a&&(c=a.detail);var d=this.ra.bind(this,c);this.b&&(d=this.da.bind(this,d));if(this.K){Enabler.setResponsiveExpanding(!0);var e=function(f){b.H=f;d()};Enabler.loadModule(studio.module.ModuleId.GDN,function(){var f=studio.sdk.gdn.getConfig();f.isInCreativeToolsetContext()?f.isInterstitial(e):d()})}else d()}};g.ia=function(){var a=this.L;Enabler.isVisible()?a():Enabler.addEventListener(studio.events.StudioEvent.VISIBLE,a)};
g.da=function(a){var b=this;this.b?(this.h&&this.b.removeEventListener("ready",this.h),this.h=function(){b.j&&b.R&&b.j.applyOverrides();O(b,a)},this.b.isDataLoaded()&&this.h(),this.b.addEventListener("ready",this.h)):a()};
var O=function(a,b){var c=!!b;if(a.g){a.c&&(a.g.removeEventListener("bindingfinished",a.c),a.c=null);var d=a.b.getData();d&&(c=a.a.getElementsBySelector("*"),c=c.concat(a.a.getPages()),a.g.bindData(d,c)?a.Z(b):(a.c=a.Z.bind(a,b),a.g.addEventListener("bindingfinished",a.c)),c=!1)}c&&b()};g=I.prototype;
g.Z=function(a){this.R=!0;this.c&&(this.g.removeEventListener("bindingfinished",this.c),this.c=null);if(this.l){var b=document.getElementsByTagName("gwd-text-helper");0<b.length&&b[0].refitAll()}D("dynamicelementsready",this);a&&a()};g.ra=function(a){this.l||(this.l=!0,document.body.style.opacity="",D("adinitialized",this,a),this.H?(a=this.a.getPage(this.a.findPageIndexByAttributeValue("expanded",!0)),this.goToPage(a.id)):this.goToPage())};
g.goToPage=function(a,b,c,d,e){var f=this.a.getPage(this.a.currentIndex);if(a=a?this.a.getPage(a):this.a.getDefaultPage()){var m=!!f&&!!a&&!this.A&&!this.H&&!f.hasAttribute("expanded")&&a.hasAttribute("expanded");f=!!f&&!!a&&!this.v&&!this.H&&f.hasAttribute("expanded")&&!a.hasAttribute("expanded");m&&this.v||f&&this.A||((this.f=a.id,b&&(this.o={transition:b,duration:c,easing:d,direction:e}),m)?this.K&&!1!==this.u?this.u&&(this.m=!0,Enabler.requestFullscreenExpand()):Enabler.requestExpand():f?this.m?
Enabler.requestFullscreenCollapse():Enabler.requestCollapse():(this.v=this.A=!1,this.M()))}};g.ga=function(){D("expandstart",this);this.u?(this.m=!0,Enabler.finishFullscreenExpand()):Enabler.finishExpand();if(!this.f){var a=this.a.getPage(this.a.findPageIndexByAttributeValue("expanded",!0));a&&(this.f=a.id)}a=this.a.getPage(this.a.currentIndex);this.A=!!a&&this.f!=a.id;window.setTimeout(this.M.bind(this),30)};
g.ea=function(){D("collapsestart",this);this.m?(Enabler.finishFullscreenCollapse(),this.m=!1):Enabler.finishCollapse();this.f||(this.reportManualClose(),this.f=this.a.getDefaultPage().id);var a=this.a.getPage(this.a.currentIndex);this.v=!!a&&this.f!=a.id;window.setTimeout(this.M.bind(this),30)};
g.ma=function(a){if(Enabler.isServingInLiveEnvironment())var b=a;else{if(!a.data||"string"!==typeof a.data)return;try{b=JSON.parse(a.data)}catch(c){return}if(b.eventType!==studio.events.StudioEvent.HOSTPAGE_SCROLL)return}D("hostpagescroll",this,b)};g.la=function(){this.l&&this.j&&(this.j.applyOverrides(),O(this,null));if(!this.f){var a=window.innerHeight>=window.innerWidth?1:2;this.J!=a&&(this.J=a,(a=this.a.getPage(this.a.currentIndex))&&window.setTimeout(this.goToPage.bind(this,a.id),0))}};
g.fa=function(a){a&&Enabler.setResponsiveSize(a.width,a.height)};g.M=function(){if(this.f){this.J=window.innerHeight>=window.innerWidth?1:2;var a=this.a.getOrientationSpecificPage(this.J,this.f);this.o?this.a.goToPage(a.id,this.o.transition,this.o.duration,this.o.easing,this.o.direction):this.a.goToPage(a.id);this.m&&a.classList.add("fs")}this.o=this.f=void 0};
g.ka=function(a){this.v=this.A=!1;if(a.target==this.a){var b=a.detail;a=b.outgoingPage;b=b.incomingPage;if(a){var c=this.X;if(a.nodeType==Node.ELEMENT_NODE)for(var d=v(c.i),e=0;e<d.length;e++){var f=C(d[e]);if(f&&x(a,f))for(var m=w(c.i,d[e]),B=0;B<m.length;B++)f.removeEventListener(m[B].event,c.I,!1)}if((a=a.querySelectorAll("video, gwd-video"))&&0<a.length)for(this.P=[];this.O.length;)studio.video.Reporter.detach(this.O.shift())}this.X.observe(b);(a=b.querySelectorAll("video, gwd-video"))&&0<a.length&&
(b=studio.video&&studio.video.Reporter,c=this.qa.bind(this),this.P=Array.prototype.slice.call(a),b?c():Enabler.loadModule(studio.module.ModuleId.VIDEO,c))}};g.qa=function(){for(var a,b;this.P.length;)if(b=this.P.shift(),a=M(b))studio.video.Reporter.attach(a,"gwd-video"==b.tagName.toLowerCase()?b.nativeElement:b,b.autoplay),this.O.push(a)};
var M=function(a){return"object"==typeof gwd&&"GwdId"in gwd?(new gwd.GwdId(a)).getString():"string"==typeof a?a:a.id},N=function(a){a=Array.prototype.slice.call(a.a.querySelectorAll("audio, video, gwd-video, gwd-youtube, gwd-youtube-livestream, gwd-audio"));for(var b=0;b<a.length;b++)a[b].pause()};customElements.define("gwd-google-ad",I);}).call(this);
