(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var f="function"==typeof Object.create?Object.create:function(a){var b=function(){};b.prototype=a;return new b},k;if("function"==typeof Object.setPrototypeOf)k=Object.setPrototypeOf;else{var l;a:{var n={s:!0},p={};try{p.__proto__=n;l=p.s;break a}catch(a){}l=!1}k=l?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var q=k,r=this||self;var t=function(a,b,c){c=void 0===c?null:c;var d=document.createEvent("CustomEvent");d.initCustomEvent(a,!0,!0,c);b.dispatchEvent(d);return d},u=function(a){a=a.timeStamp;return 5E12>a?a:a/1E3};var v=["auto","none","pan-x","pan-y"],w=2,x=null,y=!1,z=null,A=null,B=[],E=function(a,b){var c=b.changedTouches[0];null==x&&(x=c.identifier,z=c.clientX,A=c.clientY,y=!1);C(b);D(a,"pointerover",b);D(a,"pointerdown",b)},F=function(a,b,c){if(!y){var d;if(d=1!=a&&null!=z){var e=c.touches[0];d=Math.abs(e.clientX-z);e=Math.abs(e.clientY-A);d=2==a?d>e:e>d}d?(D(b,"pointercancel",c),y=!0,x=null):(D(b,"pointermove",c),c.preventDefault());A=z=null}},H=function(a,b){y||(C(b),G(b),D(a,"pointerup",b),D(a,"pointerout",
b))},G=function(a){null!=x&&I(a,function(b){x==b.identifier&&(A=z=x=null)})},C=function(a){a=a.changedTouches[0];x==a.identifier&&(a={u:a.clientX,v:a.clientY,F:a.screenX,G:a.screenY},B.push(a),setTimeout(function(b){b=B.indexOf(b);-1<b&&B.splice(b,1)}.bind(null,a),2500))},J=function(a,b,c,d){b=Math.abs(b-d);return 25>=Math.abs(a-c)&&25>=b},K=function(a,b,c,d){var e=document.createEvent("Event");e.initEvent(a,!0,!0);e.clientX=c.clientX;e.clientY=c.clientY;e.pointerId=b;e.isPrimary=d;return e},L={},
M=function(a){a=String(a.identifier);L[a]||(L[a]=w++);return L[a]},N=function(a,b,c){c.preventDefault();var d;a:{for(d=0;d<B.length;d++)if(J(c.clientX,c.clientY,B[d].u,B[d].v)||J(c.screenX,c.screenY,B[d].F,B[d].G)){d=!0;break a}d=!1}d||a.dispatchEvent(K(b,1,c,!0))},O=function(a,b,c){a.dispatchEvent(K(b,c.pointerId,c,c.isPrimary))},D=function(a,b,c){I(c,function(d){a.dispatchEvent(K(b,M(d),d,x==d.identifier))})},I=function(a,b){a=a.changedTouches;for(var c=0;c<a.length;c++)b(a[c])};var P=function(a,b){var c=document.createEvent("MouseEvent");c.initMouseEvent("tap",!0,!0,window,0,a,b,a,b,!1,!1,!1,!1,0,null);return c},R=function(a,b,c,d){return Q(a,c,d,c-b.downX,d-b.downY,c-b.lastX,d-b.lastY)},Q=function(a,b,c,d,e,m,h){var g=document.createEvent("Event");g.initEvent(a,!0,!0);g.clientX=b;g.clientY=c;g.dx=d;g.dy=e;g.ddx=m;g.ddy=h;return g};var S=function(a,b){b=Math.sqrt(a*a+b*b);return 0==b?!1:.92<Math.abs(a/b)},T=function(a,b){return Math.abs(a)>=Math.abs(b)?0<a?"swiperight":"swipeleft":0<b?"swipedown":"swipeup"};var U=function(){var a=HTMLElement.call(this)||this;a.a={};a.b=!1;a.l=t.bind(null,"hover",a);a.g=a.B.bind(a);a.i=a.C.bind(a);a.m=a.H.bind(a);a.j=a.D.bind(a);a.c=a.A.bind(a);a.o=.5;a.f=.1;a.h=!1;return a},V=HTMLElement;U.prototype=f(V.prototype);U.prototype.constructor=U;if(q)q(U,V);else for(var W in V)if("prototype"!=W)if(Object.defineProperties){var X=Object.getOwnPropertyDescriptor(V,W);X&&Object.defineProperty(U,W,X)}else U[W]=V[W];
U.prototype.connectedCallback=function(){if(!this.h){var a=1;switch(this.getAttribute("touch-action")){case "auto":a=0;break;case "pan-x":a=2;break;case "pan-y":a=3}a=void 0===a?0:a;var b=v[a];this.setAttribute("touch-action",b);this.style.touchAction=b;this.style.msTouchAction=b;void 0===r.PointerEvent&&(r.navigator.msPointerEnabled?(this.addEventListener("MSPointerOver",O.bind(null,this,"pointerover"),!1),this.addEventListener("MSPointerDown",O.bind(null,this,"pointerdown"),!1),this.addEventListener("MSPointerMove",
O.bind(null,this,"pointermove"),!1),this.addEventListener("MSPointerUp",O.bind(null,this,"pointerup"),!1),this.addEventListener("MSPointerOut",O.bind(null,this,"pointerout"),!1),this.addEventListener("MSPointerCancel",O.bind(null,this,"pointercancel"),!1)):(this.addEventListener("mouseover",N.bind(null,this,"pointerover"),!1),this.addEventListener("mousedown",N.bind(null,this,"pointerdown"),!1),this.addEventListener("mousemove",N.bind(null,this,"pointermove"),!1),this.addEventListener("mouseup",N.bind(null,
this,"pointerup"),!1),this.addEventListener("mouseout",N.bind(null,this,"pointerout"),!1),void 0!==r.ontouchstart&&(this.addEventListener("touchstart",E.bind(null,this),!1),0!=a&&this.addEventListener("touchmove",F.bind(null,a,this),!1),this.addEventListener("touchend",H.bind(null,this),!1))));this.h=!0}this.hasAttribute("swipe-velocity")&&(this.o=parseFloat(this.getAttribute("swipe-velocity")));this.hasAttribute("swipe-distance")&&(this.f=parseFloat(this.getAttribute("swipe-distance")));this.addEventListener("pointerover",
this.l,!1);this.addEventListener("pointerdown",this.g,!1);this.addEventListener("pointermove",this.i,!1);this.addEventListener("pointerup",this.m,!1);this.addEventListener("pointerout",this.j,!1);this.addEventListener("pointercancel",this.c,!1)};
U.prototype.disconnectedCallback=function(){this.removeEventListener("pointerover",this.l,!1);this.removeEventListener("pointerdown",this.g,!1);this.removeEventListener("pointermove",this.i,!1);this.removeEventListener("pointerup",this.m,!1);this.removeEventListener("pointerout",this.j,!1);this.removeEventListener("pointercancel",this.c,!1)};
U.prototype.B=function(a){if(a.isPrimary){var b=String(a.pointerId);this.a[b]||(this.a[b]={downX:a.clientX,downY:a.clientY,downTime:u(a),lastX:a.clientX,lastY:a.clientY,tracking:!1});this.b=!1}};
U.prototype.C=function(a){a.preventDefault();var b=this.a[String(a.pointerId)];if(b){if(10<Math.abs(b.downX-a.clientX)||10<Math.abs(b.downY-a.clientY))this.b=!0;b.tracking||(this.dispatchEvent(Q("trackstart",b.downX,b.downY,0,0,0,0)),b.tracking=!0);this.dispatchEvent(R("track",b,a.clientX,a.clientY));b.lastX=a.clientX;b.lastY=a.clientY}};U.prototype.H=function(a){Y(this,a)&&(this.b||this.dispatchEvent(P(a.clientX,a.clientY)))};U.prototype.D=function(a){Y(this,a);t("hoverend",this)};
var Y=function(a,b){var c=a.a[String(b.pointerId)];if(c){if(c.tracking){a.dispatchEvent(R("trackend",c,b.clientX,b.clientY));var d=b.clientX-c.downX,e=b.clientY-c.downY;a:{var m=u(b)-c.downTime;var h=a.f;var g=d/m;m=e/m;if(Math.abs(Math.sqrt(g*g+m*m))<a.o)h=!1;else switch(T(d,e)){case "swipeup":case "swipedown":h=S(e,d)&&Math.abs(e)>=a.clientHeight*h;break a;case "swipeleft":case "swiperight":h=S(d,e)&&Math.abs(d)>=a.clientWidth*h;break a;default:h=!1}}h&&t(T(d,e),a)}Z(a,b)}return c};
U.prototype.A=function(a){Z(this,a);this.b=!0};var Z=function(a,b){b=String(b.pointerId);a.a[b]&&delete a.a[b]};customElements.define("gwd-gesture",U);}).call(this);
