(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var f,g="function"==typeof Object.create?Object.create:function(a){var b=function(){};b.prototype=a;return new b},h;if("function"==typeof Object.setPrototypeOf)h=Object.setPrototypeOf;else{var k;a:{var l={o:!0},m={};try{m.__proto__=l;k=m.o;break a}catch(a){}k=!1}h=k?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}
var n=h,q=this||self,r=function(a,b){function d(){}d.prototype=b.prototype;a.I=b.prototype;a.prototype=new d;a.prototype.constructor=a;a.J=function(c,e,J){for(var w=Array(arguments.length-2),p=2;p<arguments.length;p++)w[p-2]=arguments[p];return b.prototype[e].apply(c,w)}};var t=function(a,b,d){d=void 0===d?null:d;var c=document.createEvent("CustomEvent");c.initCustomEvent(a,!0,!0,d);b.dispatchEvent(c);return c};function u(a){if(Error.captureStackTrace)Error.captureStackTrace(this,u);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))}r(u,Error);u.prototype.name="CustomError";var v=function(a,b){a=a.split("%s");for(var d="",c=a.length-1,e=0;e<c;e++)d+=a[e]+(e<b.length?b[e]:"%s");u.call(this,d+a[c])};r(v,u);v.prototype.name="AssertionError";var x=function(a,b,d){if(!a){var c="Assertion failed";if(b){c+=": "+b;var e=Array.prototype.slice.call(arguments,2)}throw new v(""+c,e||[]);}return a},y=function(a,b){throw new v("Failure"+(a?": "+a:""),Array.prototype.slice.call(arguments,1));};var A=function(a,b){this.f=b===z?a:""};A.prototype.A=!0;A.prototype.v=function(){return this.f.toString()};A.prototype.toString=function(){return"SafeUrl{"+this.f+"}"};var B=function(a){if(a instanceof A&&a.constructor===A)return a.f;var b=typeof a;y("expected object of type SafeUrl, got '"+a+"' of type "+("object"!=b?b:a?Array.isArray(a)?"array":b:"null"));return"type_error:SafeUrl"},C=/^(?:(?:https?|mailto|ftp):|[^:/?#]*(?:[/?#]|$))/i,z={};var D=[],E=function(a){a=D.indexOf(a);0<=a&&D.splice(a,1)};document.addEventListener("click",function(a){for(var b=0;b<D.length;b++)if(25>Math.abs(a.clientX-D[b].s)&&25>Math.abs(a.clientY-D[b].u)||25>Math.abs(a.screenX-D[b].G)&&25>Math.abs(a.screenY-D[b].H))D.splice(b,1),a.stopPropagation(),a.preventDefault()},!0);var F=function(){var a=HTMLElement.call(this)||this;a.l=0;a.m=0;a.c=null;a.h=null;a.b=null;a.g=null;a.i=a.B.bind(a);a.a=!0;return a},G=HTMLElement;F.prototype=g(G.prototype);
F.prototype.constructor=F;if(n)n(F,G);else for(var H in G)if("prototype"!=H)if(Object.defineProperties){var I=Object.getOwnPropertyDescriptor(G,H);I&&Object.defineProperty(F,H,I)}else F[H]=G[H];F.I=G.prototype;f=F.prototype;f.connectedCallback=function(){this.b||(this.c=this.j.bind(this),this.h=this.F.bind(this),this.b=this.D.bind(this),this.g=this.C.bind(this));this.addEventListener("click",this.c,!1);this.addEventListener("touchstart",this.h,!1);this.addEventListener("action",this.i,!1)};
f.disconnectedCallback=function(){this.removeEventListener("click",this.c,!1);this.removeEventListener("touchstart",this.h,!1);this.removeEventListener("action",this.i,!1)};f.j=function(a){this.a&&t("action",this,a);this.a=!0};f.F=function(a){this.addEventListener("touchmove",this.b,!1);this.addEventListener("touchend",this.g,!1);a=a.touches[0];this.l=a.clientX;this.m=a.clientY};
f.C=function(a){this.j(a);this.removeEventListener("touchmove",this.b,!1);this.removeEventListener("touchend",this.g,!1);a=a.changedTouches[0];a={s:a.clientX,u:a.clientY,G:a.screenX,H:a.screenY};D.push(a);setTimeout(E.bind(null,a),2500)};f.D=function(a){a=a.touches[0];this.a=this.a&&10>=Math.abs(this.l-a.clientX)&&10>=Math.abs(this.m-a.clientY)};
f.B=function(a){var b=this.getAttribute("exit-id"),d=this.getAttribute("product-index"),c=this.getAttribute("exit-override-url");c&&!t("tapareaexit",this,{"exit-id":b,url:c,"product-index":d,"action-event":a.detail}).detail.handled&&(c instanceof A?a=c:(a=c,a instanceof A||(a="object"==typeof a&&a.A?a.v():String(a),x(C.test(a),"%s does not match the safe URL pattern",a)||(a="about:invalid#zClosurez"),a=new A(a,z))),q.open(B(a),""))};customElements.define("gwd-taparea",F);}).call(this);
