# Generated by Django 3.1.3 on 2020-11-17 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='address',
        ),
        migrations.AddField(
            model_name='address',
            name='detail',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
