# Generated by Django 3.1.2 on 2020-12-09 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, height_field=600, null=True, upload_to='category/', verbose_name='عکس گروه', width_field=600),
        ),
    ]
