# Generated by Django 3.1.3 on 2020-11-17 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20201116_0800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.JSONField(blank=True, null=True, verbose_name='توضیحات گروه بندی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='description',
            field=models.JSONField(blank=True, null=True, verbose_name='توضیحات طبقه بندی'),
        ),
    ]
