# Generated by Django 3.1.3 on 2020-11-17 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20201117_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='its_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=35, unique=True, verbose_name='گروه'),
        ),
    ]
