# Generated by Django 3.1.2 on 2020-12-09 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20201209_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='productprice',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, default='1999-1-1', verbose_name='datetime'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productbrand',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/brands/', verbose_name='Brand image'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='image',
            field=models.ImageField(upload_to='sub-category/', verbose_name='عکس طبقه بندی'),
        ),
    ]
