# Generated by Django 3.1.2 on 2020-12-06 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20201117_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.category'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='its_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', related_query_name='sub_category', to='product.category'),
        ),
    ]
