# Generated by Django 3.1.2 on 2020-12-19 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20201219_1549'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='subcategory',
            constraint=models.UniqueConstraint(fields=('title', 'its_category'), name='unique_order'),
        ),
    ]
