# Generated by Django 3.1.4 on 2021-01-12 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_auto_20210113_0008'),
        ('user', '0008_auto_20210104_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_last_login',
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.RESTRICT, primary_key=True, serialize=False, to='user.user')),
                ('image', models.ImageField(blank=True, null=True, upload_to='./res/profile_photo')),
                ('user_last_login', models.DateTimeField(auto_now_add=True)),
                ('address', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.address')),
            ],
        ),
    ]
