# Generated by Django 3.1.2 on 2020-12-06 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20201206_0953'),
        ('pardakht', '0003_auto_20201118_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchases',
            name='user',
        ),
        migrations.AddField(
            model_name='purchases',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.user'),
            preserve_default=False,
        ),
    ]
